name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
       - name: Configuring git environment.
         run: |
            git config --global user.name RahulPalXDA
            git config --global user.email RahulPal.XDA@gmail.com
            git config --global core.editor nano
            sudo -E apt-get -qq update && sudo -E apt-get -qq upgrade
            sudo -E apt-get -qq install bc python2 python3 python-is-python3 wget

       - name: Uploading.
         run: |
             wget https://releases.ubuntu.com/22.04.3/ubuntu-22.04.3-desktop-amd64.iso
             echo "a435f6f393dda581172490eda9f683c32e495158a780b5a1de422ee77d98e909 *ubuntu-22.04.3-desktop-amd64.iso" | shasum -a 256 --check
             curl -T "ubuntu-22.04.3-desktop-amd64.iso" https://pixeldrain.com/api/file/
